# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1iA6i_vAQiGoRq0_w1pByeoH3CTsx6L
"""

# Commented out IPython magic to ensure Python compatibility.
# import required modules and libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# Load the Dataset
data = pd.read_csv('/content/Student_Performance.csv')
data.sample(3)

#Getting information about the dataset
data.info()

data.describe()

# Univariate EDA
data['Extracurricular Activities'] = data['Extracurricular Activities'].apply(lambda x: 1 if x == 'Yes' else 0)
data.sample(4)

data.corr()

sns.regplot(x ="Hours Studied",y="Performance Index",data = data)

sns.regplot(x ="Previous Scores",y="Performance Index",data = data)

sns.regplot(x ="Sleep Hours",y="Performance Index",data = data)

sns.regplot(x ="Sample Question Papers Practiced",y="Performance Index",data = data)

X = data.iloc[:,0:-1]
y = data.iloc[:,-1]
X.shape, y.shape

# Split dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#standardize the dataset
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()

x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)

x_test

#Train teh model by Linear Regression
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(x_train, y_train)

reg.coef_

reg.intercept_

#Prediction on test data
y_pred = reg.predict(x_test)
y_pred, y_test.values

residual = y_test.values - y_pred
sns.distplot(residual, hist = False)

plt.scatter(y_pred, residual)

# MAE, MSE, SMSE, r2 score calculate
from math import sqrt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print('MAE', mean_absolute_error(y_test, y_pred) )
print('MSE', mean_squared_error(y_test, y_pred) )
print('SMSE', sqrt(mean_squared_error(y_test, y_pred)))
print('r2 score', r2_score(y_test, y_pred))
r2 =  r2_score(y_test, y_pred)



Adjusted_r2_score = 1- (((1-r2)*(len(y_train) + len(y_test)-1))/(len(y_train) + len(y_test)-x_train.shape[1]-1))
print('Adjusted r2 score', Adjusted_r2_score)